jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # --- NEW DEBUGGING STEP ---
      - name: List files in the repository
        run: ls -R
      # --- END OF DEBUGGING STEP ---

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news fetching script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python fetch_script.py